<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2026 YOFC IOT and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
     YOFC IOT

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>kura-yofc-runtime</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>kura-yofc-runtime.bundles</artifactId>
    <packaging>pom</packaging>
    <name>kura-yofc-runtime bundle parent</name>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <netty.version>4.2.16.Final</netty.version>
        <maven-bundle-plugin.version>6.0.0</maven-bundle-plugin.version>
        <osgi-dp-plugin.version>0.5.2</osgi-dp-plugin.version>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.felix</groupId>
                    <artifactId>maven-bundle-plugin</artifactId>
                    <version>${maven-bundle-plugin.version}</version>
                    <extensions>true</extensions>
                </plugin>
                <plugin>
                    <groupId>com.github.heyoulin</groupId>
                    <artifactId>osgi-dp</artifactId>
                    <version>${osgi-dp-plugin.version}</version>
                    <extensions>true</extensions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <modules>
        <module>com.yofc.iot.runtime</module>
    </modules>
</project>
